version: '3.3'

services:
  clubmate:
    image: clubmate:latest
    links:
      - redis:redis
      - mysql:db
    container_name: clubmatedude
    env_file:
      - mate-variables.env
    environment:
      - VIRTUAL_HOST=mate.brnhaed.de
  mate-worker:
    links:
      - redis:redis
      - mysql:db
    image: clubmate:latest
    entrypoint: celery worker -A app.celery -B --loglevel=info
    env_file:
      - mate-variables.env
  redis:
    image: redis:latest
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=

networks:
  default:
    external:
      name: data_webproxy
