"""language saved for user

Revision ID: 48546fdb930b
Revises: bfe13eb1531e
Create Date: 2019-12-14 16:58:40.816097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48546fdb930b'
down_revision = 'bfe13eb1531e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lang', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lang')
    # ### end Alembic commands ###
