"""offers

Revision ID: 84d40eea5067
Revises: 7dcbb29062fb
Create Date: 2020-02-24 19:18:01.212156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d40eea5067'
down_revision = '7dcbb29062fb'
branch_labels = None
depends_on = None

def get_consumption_table():
    meta = sa.MetaData()
    return sa.Table(
        'consumption',meta,
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Integer(), nullable=True),
        sa.Column('price', sa.Float(), nullable=True),
        sa.Column('drink_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('time', sa.DateTime(), nullable=True),
        sa.Column('billed', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['drink_id'], ['drink.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    bind = op.get_bind()
    if bind.engine.name == 'mysql':
        op.create_foreign_key(None, 'consumption', 'offer', ['offer_id'], ['id'])
    op.add_column('consumption', sa.Column('offer_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'consumption', type_='foreignkey')
    op.drop_column('consumption', 'offer_id')
    op.drop_table('offer')
    # ### end Alembic commands ###
