"""offers

Revision ID: 84d40eea5067
Revises: 7dcbb29062fb
Create Date: 2020-02-24 19:18:01.212156

"""
from alembic import op, context
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d40eea5067'
down_revision = '7dcbb29062fb'
branch_labels = None
depends_on = None

def get_invoice_table():
    meta = sa.MetaData()
    return sa.Table('invoice',meta,
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sum', sa.Float(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('date', sa.DateTime(), nullable=True),
        sa.Column('paypalme', sa.String(length=64), nullable=True),
        sa.Column('paid', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

def get_user_table():
    meta = sa.MetaData()
    return sa.Table('user',meta,
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=64), nullable=True),
        sa.Column('email', sa.String(length=120), nullable=True),
        sa.Column('password_hash', sa.String(length=128), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

def get_consumption_table():
    meta = sa.MetaData()
    return sa.Table(
        'consumption',meta,
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Integer(), nullable=True),
        sa.Column('price', sa.Float(), nullable=True),
        sa.Column('product_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('time', sa.DateTime(), nullable=True),
        sa.Column('billed', sa.Boolean(), nullable=True),
        sa.Column('offer_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.add_column('invoice', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.add_column('consumption', sa.Column('offer_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('paypal', sa.String(length=50), nullable=True))

    bind = op.get_bind()
    if bind.engine.name == 'mysql':
        op.create_foreign_key(None, 'consumption', 'offer', ['offer_id'], ['id'])
        op.create_foreign_key(None, 'invoice', 'user', ['supplier_id'], ['id'])
        op.drop_column('invoice', 'paypalme')
    else:
        with op.batch_alter_table('invoice', copy_from=get_invoice_table()) as bop:
            bop.drop_column('paypalme')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.engine.name == 'mysql':
        op.drop_constraint(None, 'consumption', type_='foreignkey')
        op.drop_column('consumption', 'offer_id')
    else:
        with op.batch_alter_table('consumption', copy_from=get_consumption_table()) as bop:
            bop.drop_column('offer_id')
        with op.batch_alter_table('user', copy_from=get_user_table()) as bop:
            bop.drop_column('paypal')
    op.drop_table('offer')
    # ### end Alembic commands ###
