"""offers

Revision ID: 84d40eea5067
Revises: 2a454f9ebc31
Create Date: 2020-02-27 21:12:55.950327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = '84d40eea5067'
down_revision = '2a454f9ebc31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consumption', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('invoice_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_con_supplier_id', 'user', ['supplier_id'], ['id'])
        batch_op.create_foreign_key('fk_con_invoice_id', 'invoice', ['invoice_id'], ['id'])

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sent', sa.Boolean(), nullable=False))
        batch_op.create_foreign_key('fk_inv_supplier_id', 'user', ['supplier_id'], ['id'])
        batch_op.drop_column('paypalme')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paypal', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('paypal')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paypalme', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_constraint('fk_inv_supplier_id', type_='foreignkey')
        batch_op.drop_column('supplier_id')

    with op.batch_alter_table('consumption', schema=None) as batch_op:
        batch_op.drop_constraint('fk_con_supplier_id', type_='foreignkey')
        batch_op.drop_constraint('fk_con_invoice_id', type_='foreignkey')
        batch_op.drop_column('invoice_id')
        batch_op.drop_column('supplier_id')

    op.drop_table('offer')
    # ### end Alembic commands ###
