"""added iniciator to consumption

Revision ID: 89d9c7059115
Revises: b073314db20f
Create Date: 2020-11-14 10:25:38.742620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89d9c7059115'
down_revision = 'b073314db20f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumption', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iniciator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_iniciator_id', 'user', ['iniciator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumption', schema=None) as batch_op:
        batch_op.drop_constraint('fk_iniciator_idone', type_='foreignkey')
        batch_op.drop_column('iniciator_id')

    # ### end Alembic commands ###
